### ISSUE TITLE
Error: Cannot find module './packager/babelRegisterOnly'

### ISSUE THREAD

**Issue by BrianJVarley** [mcnamee/react-native-starter-app#63]
I've cloned the project today after running a fresh `npm install`, then ran to open the app on emulator:

`react-native run-android`

But got an error telling that `Error: Cannot find module './packager/babelRegisterOnly'`
Any ideas what's going on there? Don't see any similar issues open matching the error. Thanks

Full error:

$ react-native run-android

```
module.js:327
    throw err;
    ^

Error: Cannot find module './packager/babelRegisterOnly'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Brian\Documents\Visual Studio 2013\Projects\react-native-starter-app\node_modules\react-native\cli.js:11:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)




```

**Comment by BrianJVarley** [comment]
Solve by installing and reinstalling react-native-cli:

1.delete node modules folder

2.
`npm uninstall -g react-native cli`
`npm install -g react-native cli`
`npm install`
