### ISSUE TITLE
@providesModule naming collision

### ISSUE THREAD

**Issue by fawwaz** [mcnamee/react-native-starter-app#75]
I download your latest release (version 2). I am avoding to use the master branch since travis-ci said it failed to build. I thought it will run smoothly, as I start running `react-native start`, I got this message : 
```
React packager ready.

[5/8/2017, 9:56:39 AM] <START> Initializing Packager
[5/8/2017, 9:56:39 AM] <START> Building in-memory fs for JavaScript
[5/8/2017, 9:56:40 AM] <END>   Building in-memory fs for JavaScript (76ms)
[5/8/2017, 9:56:40 AM] <START> Building Haste Map
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /home/fawwaz.muhammad/personal/bukalapak/react-native-starter-app-2.0.0/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /home/fawwaz.muhammad/personal/bukalapak/react-native-starter-app-2.0.0/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /home/fawwaz.muhammad/personal/bukalapak/react-native-starter-app-2.0.0/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /home/fawwaz.muhammad/personal/bukalapak/react-native-starter-app-2.0.0/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/home/fawwaz.muhammad/personal/bukalapak/react-native-starter-app-2.0.0/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at /home/fawwaz.muhammad/personal/bukalapak/react-native-starter-app-2.0.0/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:134:31
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! StarterKit@1.0.0 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the StarterKit@1.0.0 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the StarterKit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs StarterKit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls StarterKit
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fawwaz.muhammad/.npm/_logs/2017-05-08T02_56_40_527Z-debug.log
```

**Comment by mcnamee** [comment]
Hi @fawwaz 
I believe this one was solved from https://github.com/mcnamee/react-native-starter-app/issues/70 if you grab the latest from Master

**Comment by fawwaz** [comment]
Yeah, I install `react-native-router-flux` version 0.38.0 and it works normally.
